// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package example.domain;

import example.domain.ItemGroup;

privileged aspect ItemGroup_Roo_JavaBean {
    
    public String ItemGroup.getName() {
        return this.name;
    }
    
    public void ItemGroup.setName(String name) {
        this.name = name;
    }
    
}
