// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package example.domain;

import example.domain.WorkingModel;
import example.domain.WorkingModelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WorkingModelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WorkingModelDataOnDemand: @Component;
    
    private Random WorkingModelDataOnDemand.rnd = new SecureRandom();
    
    private List<WorkingModel> WorkingModelDataOnDemand.data;
    
    public WorkingModel WorkingModelDataOnDemand.getNewTransientWorkingModel(int index) {
        WorkingModel obj = new WorkingModel();
        setInfoType(obj, index);
        setModelId(obj, index);
        setName(obj, index);
        setNoTran(obj, index);
        return obj;
    }
    
    public void WorkingModelDataOnDemand.setInfoType(WorkingModel obj, int index) {
        int infoType = index;
        obj.setInfoType(infoType);
    }
    
    public void WorkingModelDataOnDemand.setModelId(WorkingModel obj, int index) {
        int modelId = index;
        obj.setModelId(modelId);
    }
    
    public void WorkingModelDataOnDemand.setName(WorkingModel obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void WorkingModelDataOnDemand.setNoTran(WorkingModel obj, int index) {
        int noTran = index;
        obj.setNoTran(noTran);
    }
    
    public WorkingModel WorkingModelDataOnDemand.getSpecificWorkingModel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WorkingModel obj = data.get(index);
        Long id = obj.getId();
        return WorkingModel.findWorkingModel(id);
    }
    
    public WorkingModel WorkingModelDataOnDemand.getRandomWorkingModel() {
        init();
        WorkingModel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WorkingModel.findWorkingModel(id);
    }
    
    public boolean WorkingModelDataOnDemand.modifyWorkingModel(WorkingModel obj) {
        return false;
    }
    
    public void WorkingModelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WorkingModel.findWorkingModelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WorkingModel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WorkingModel>();
        for (int i = 0; i < 10; i++) {
            WorkingModel obj = getNewTransientWorkingModel(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
